#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------


    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.server_name = "Seafile"
    args.admin_password = "Sup3rS3cr3t"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.b4ba63d.name = "Pre packaging v2 (Old_version_for_CI_6 branch)"
    test_upgrade_from.d9381d3.name = "Version 7.1 (Old_version_for_CI_4 branch)"
    test_upgrade_from.fb2a04e.name = "Version 8.x (Old_version_for_CI_5 branch)"
