#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------


    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.server_name = "Seafile"
    args.admin_password = "Sup3rS3cr3t"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.b5fd940.name = "Pre packaging v2"
    test_upgrade_from.3ce35d3.name = "Version 7.1 Old version for CI 4 branch"
    test_upgrade_from.97c0b2f.name = "Version 8.x Old version for CI 5 branch"
