# WARNING: Don't edit this file. All change will be removed after each app upgrade

[fileserver]
port = __PORT_FILESERVER__

# Set maximum upload file size to xx M.
# If not configured, there is no file size limit for uploading.
max_upload_size=__MAX_UPLOAD_SIZE__

# Set maximum download directory size to xx M.
# Default is 100M.
max_download_dir_size=__MAX_DOWNLOAD_DIR_SIZE__

use_go_fileserver = true

[database]
type = mysql
host = 127.0.0.1
port = 3306
user = __DB_USER__
password = __DB_PWD__
db_name = __DB_NAME__
connection_charset = utf8
