#!/bin/bash

source ./experimental_helper.sh
source ./_common.sh
source /usr/share/yunohost/helpers

ynh_app_config_apply() {
    _ynh_app_config_apply
    ynh_config_add_nginx
    ynh_config_add --template=seafile.conf --destination="$install_dir"/conf/seafile.conf

    set_permission
}

#=================================================
# SELECT THE ACTION FOLLOWING THE GIVEN ARGUMENT
#=================================================
ynh_app_config_run "$1"
