#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Import common cmd
source ./_common.sh

#=================================================
# STANDARD REMOVE
#=================================================

ynh_script_progression "Stoping services..."

# Stop all services
ynh_systemctl --service="$app" --action=stop
ynh_systemctl --service=seahub --action=stop
ynh_systemctl --service="$app"-notification.service --action=stop
ynh_systemctl --service="$app"-doc-server.service --action=stop
ynh_systemctl --service="$app"-doc-converter.service --action=stop
ynh_systemctl --service="$app"-thumbnail.service --action=stop

# Force to kill all process in case of a process is not stoped cleanly
pkill -f seafile-controller || true
pkill -f seaf-server || true
pkill -f ccnet-server || true
pkill -f seahub || true

# Remove databases
ynh_script_progression "Removing databases..."
ynh_''mysql_drop_db ccnetdb
ynh_''mysql_drop_db seahubdb

ynh_redis_remove_db "$redis_db"

# Remove systemd service
ynh_script_progression "Removing systemd units..."
ynh_config_remove_systemd "$app"
ynh_config_remove_systemd seahub
ynh_config_remove_systemd "$app-notification"
ynh_config_remove_systemd "$app-doc-server"
ynh_config_remove_systemd "$app-doc-converter"
ynh_config_remove_systemd "$app-thumbnail"

# Remove NGINX config
ynh_script_progression "Removing NGINX configuration..."
ynh_config_remove_nginx

# Remove logrotate
ynh_config_remove_logrotate

# Remove the dedicated Fail2Ban config
ynh_script_progression "Removing Fail2Ban configuration..."
ynh_config_remove_fail2ban

ynh_script_progression "Removing Seafile service..."
yunohost service remove "$app"
yunohost service remove seahub
yunohost service remove "$app"-notification
yunohost service remove "$app-doc-server"
yunohost service remove "$app-doc-converter"
yunohost service remove "$app-thumbnail"

ynh_script_progression "Removal of $app completed"

sleep 1
