#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

#=================================================
# STANDARD REMOVE
#=================================================

ynh_script_progression "Stoping services..."

# Stop all services
ynh_systemctl --service="$app" --action=stop
ynh_systemctl --service=seahub --action=stop
ynh_systemctl --service="$app"-notification.service --action=stop

# Force to kill all process in case of a process is not stoped cleanly
pkill -f seafile-controller || true
pkill -f seaf-server || true
pkill -f ccnet-server || true
pkill -f seahub || true

# Remove databases
ynh_script_progression "Removing databases..."
ynh_''mysql_drop_db ccnetdb
ynh_''mysql_drop_db seahubdb

# Remove systemd service
ynh_script_progression "Removing systemd units..."
ynh_config_remove_systemd "$app"
ynh_config_remove_systemd seahub
ynh_config_remove_systemd "$app"-notification

# Remove nginx config
ynh_script_progression "Removing nginx configuration..."
ynh_config_remove_nginx

# Remove logrotate
ynh_config_remove_logrotate

# Remove the dedicated fail2ban config
ynh_script_progression "Removing fail2ban configuration..."
ynh_config_remove_fail2ban

ynh_script_progression "Removing seafile service..."
yunohost service remove "$app"
yunohost service remove seahub
yunohost service remove "$app"-notification

ynh_script_progression "Removal of $app completed"

sleep 1
