#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Import common cmd
source ./_common.sh
source ./ynh_setup_source

installed_version="${YNH_APP_CURRENT_VERSION/~ynh*/}"

ensure_vars_set

if [ "$YNH_APP_CURRENT_VERSION" == '-' ] || ynh_app_upgrading_from_version_before_or_equal_to '7.0~ynh1'; then
    ynh_die "Upgrade from this version not supported"
fi

ynh_script_progression "Stoping services..."

ynh_systemctl --service="$app" --action=stop
ynh_systemctl --service=seahub --action=stop
ynh_systemctl --service="$app"-notification.service --action=stop
ynh_systemctl --service="$app"-doc-server.service --action=stop
ynh_systemctl --service="$app"-doc-converter.service --action=stop
sleep 5
pkill -f seafile-controller || true
pkill -f seaf-server || true
pkill -f ccnet-server || true
pkill -f seahub || true

# Migrate DB name if needed
if mysqlshow | grep -q seafiledb; then
    mysqlconn="mysql -u root"
    sql_mv_params=$($mysqlconn -N -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES \
                            WHERE table_schema='seafiledb'")
    for name in $sql_mv_params; do
        $mysqlconn -e "RENAME TABLE seafiledb.$name to $db_name.$name";
    done;
    $mysqlconn -e "DROP DATABASE seafiledb"
    ynh_replace --match='db_name = seafiledb' --replace='db_name = seafile' --file="$install_dir"/conf/seafile.conf
    sed -i "s|password\s*=\s*.*^|password = $db_pwd|g" "$install_dir"/conf/seafile.conf
fi

# Set missing settings
ynh_app_setting_set_default --key=seahub_secret_key --value="$(grep -P 'SECRET_KEY\s*=\s*".+"' "$install_dir"/conf/seahub_settings.py | cut -d'"' -f2)"

#
# Update data dir if needed
#

# Move if needed old /home/yunohost.app/seafile-data dir to /home/yunohost.app/seafile/seafile-data
if [ -e /home/yunohost.app/seafile-data ]; then
    if [ -e "$data_dir" ]; then
        mv "$data_dir" "${data_dir}_$(date '+%Y%m%d.%H%M%S')"
    fi
    mkdir -p "$data_dir"
    mv /home/yunohost.app/seafile-data "$data_dir"/
fi

# In case of seafile-data content was directly stored in /home/yunohost.app/seafile
if [ -e "$data_dir"/storage ]; then
    mkdir -p "$data_dir"/seafile-data
    mv -t "$data_dir"/seafile-data "$data_dir"/{commits,fs,httptemp,library-template,storage,tmpfiles,webdavtmp} || true # In case of some of dir don't exist
fi

# Move seahub data to /home/yunohost.app/seafile/seahub-data
if [ -e "$install_dir"/seahub-data ] && [ ! -L "$install_dir"/seahub-data ]; then
    if [ -e "$data_dir"/seahub-data ]; then
        mv "$data_dir"/seahub-data "$data_dir/seahub-data_$(date '+%Y%m%d.%H%M%S')"
    fi
    mv "$install_dir"/seahub-data "$data_dir"/
fi

# Move logs storage to /var/log/seafile
if [ -e "$install_dir"/logs ] && [ ! -L "$install_dir"/logs ]; then
    if [ -e /var/log/"$app" ]; then
        mv /var/log/"$app" /var/log/"${app}_$(date '+%Y%m%d.%H%M%S')"
    fi
    mv "$install_dir"/logs  /var/log/"${app}"
fi

if [ -z "${redis_db:-}" ]; then
    redis_db=$(ynh_redis_get_free_db)
    ynh_app_setting_set --app="$app" --key=redis_db --value="$redis_db"
fi

# Ensure all data dir are created
mkdir -p /var/log/"$app"
mkdir -p "$data_dir"/{seafile-data,seahub-data,notification-data}
mkdir -p "$install_dir"/{conf,ccnet,seadoc-conf}

ynh_script_progression "Upgrading source files..."

# Download new version from sources
ynh_script_progression "Installing sources files..."
if [ "$YNH_APP_UPGRADE_TYPE" == UPGRADE_APP ]; then
    install_source
fi

ynh_script_progression "Configuring application..."

# permission to execute update script and expect helper
set_permission

configure_env_files

# do the upgrade    ( the ";&" syntax mean when it go in the first case which is true it do all the next case)
case "$installed_version" in
"4."* )
	# Update seafile by script
	ynh_die "Upgrade form the version 4.x was removed. Upgrade from this version won't be supported any more."
;&
"5."* )
	# Update Seafile by script
	ynh_die "Upgrade form the version 5.x was removed. Upgrade from this version won't be supported any more."
;&
"6."* )
	ynh_die "Upgrade form the version 6.x was removed. Upgrade from this version won't be supported any more."
;&
"7.0"* )
    # Fix file comment
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/seahub.sh" python-env python3 "/opt/seafile/seafile-server-$seafile_version/seahub/manage.py" migrate_file_comment

    # Update Seafile by script
    ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/upgrade_7.0_7.1.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/upgrade_7.0_7.1.sh"

    # Fix seafile data link. Look like that the upgrade script of seafile don't always work correctly
    if [ -e "$install_dir"/seafile-data ]; then
        old_data_dir_path="$install_dir/seafile-data$(date '+%Y%m%d.%H%M%S')"
        mv "$install_dir/seafile-data" "$old_data_dir_path"
    fi
    ln -s "$data_dir" "$install_dir"/seafile-data
;&
"7.1."* )
    ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/upgrade_7.1_8.0.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/upgrade_7.1_8.0.sh"
;&
"8."* )
    ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/upgrade_8.0_9.0.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/upgrade_8.0_9.0.sh"
;&
"9."* )
    ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/upgrade_9.0_10.0.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/upgrade_9.0_10.0.sh"
;&
"10."* )
    ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/upgrade_10.0_11.0.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/upgrade_10.0_11.0.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/seahub.sh" python-env python3 "/opt/seafile/seafile-server-$seafile_version/migrate_ldapusers.py"
;&
"11."* )
    ynh_safe_rm "$install_dir"/conf/ccnet.conf

    ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/upgrade_11.0_12.0.sh"
    run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/upgrade_11.0_12.0.sh"
;&
esac

ynh_replace --match='read dummy' --replace='# patched' --file="$seafile_code/upgrade/minor-upgrade.sh"
run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version/upgrade/minor-upgrade.sh"

# Clean expired sessions, cf: https://manual.seafile.com/12.0/administration/clean_database/
run_seafile_cmd "/opt/seafile/seafile-server-$seafile_version//seahub.sh" python-env python3 seahub/manage.py clearsessions

# Clean URL in config in DB
clean_url_in_db_config

# Update Seafile config files
if [ "$(lsb_release -c -s)" == bullseye ]; then
    # Fix header for retro compability on YunoHost 11
    ynh_replace --match="'HTTP_YNH_USER_EMAIL'" --replace="'HTTP_EMAIL'" --file="../conf/seahub_settings.py"
fi
ynh_config_add --jinja --template=seahub_settings.py --destination="$install_dir"/conf/seahub_settings.py
ynh_config_add --template=seafile.conf --destination="$install_dir"/conf/seafile.conf
ynh_config_add --template=gunicorn.conf.py --destination="$install_dir"/conf/gunicorn.conf.py
ynh_config_add --template=seafdav.conf --destination="$install_dir"/conf/seafdav.conf
ynh_config_add --template=seafevents.conf --destination="$install_dir"/conf/seafevents.conf

# Fix local warning
ynh_replace --match=en_US.UTF-8 --replace="${LANG:-'en_US.UTF-8'}" --file="$seafile_code/seahub.sh"

#=================================================

# Config NGINX
ynh_config_add_nginx 'seahub_port fileserver_port webdav_port'

# Add Seafile Server to startup
ynh_script_progression "Configuring $app's systemd service..."
configure_systemd_services

# register YunoHost service
yunohost service add "$app" --description 'Main service for seafile server.'
yunohost service add seahub --description 'Seafile server web interface.'
yunohost service add "$app"-notification --description 'Seafile client notification server.'
yunohost service add "$app-doc-server" --description 'Seafile online collaborative document editor server.'
yunohost service add "$app-doc-converter" --description 'Seafile online collaborative document editor converter.'
if [ "$YNH_ARCH" != arm64 ]; then
    yunohost service add "$app-thumbnail" --description 'Server to create thumbnails for images, videos, PDFs and other file types.'
fi

#=================================================

# Set all permissions
ynh_script_progression "Protecting directory..."
set_permission

# Add logrotate
ynh_script_progression "Configuring log rotation..."
ynh_config_add_logrotate /var/log/"$app"

# Add Fail2Ban
ynh_script_progression "Configuring fail2ban..."
ynh_config_add_fail2ban --logpath="$install_dir"/logs/seahub.log

# delete Seafile cache

# restart Seafile server
ynh_script_progression "Starting seafile services..."
ynh_systemctl --service="$app" --wait_until='Seafile server started' --log_path=systemd
sleep 2
ynh_systemctl --service=seahub --wait_until='Seahub is started' --log_path=systemd
ynh_systemctl --service="$app"-notification.service --wait_until="notification server started" --log_path=systemd
ynh_systemctl --service="$app"-doc-server.service --wait_until="server is serve on http://127.0.0.1" --log_path=systemd
ynh_systemctl --service="$app"-doc-converter.service --log_path=systemd
if [ "$YNH_ARCH" != arm64 ]; then
    ynh_systemctl --service="$app"-thumbnail.service --log_path=systemd
fi

# remove old version files
ynh_script_progression "Cleaning system and updating settings..."
for f in "$install_dir"/seafile-server-*;do
    if [[ ! "$f" =~ ${seafile_version//./\\.}|latest ]]; then
        ynh_safe_rm "$f"
    fi
done

ynh_script_progression "Upgrade of $app completed"
